name: download_ranges

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  wget:
    runs-on: ubuntu-latest
    steps:
    - name: wget
      uses: wei/wget@v1
      with:
        args: -O ranges.json https://cdn.nuclei.sh/
  push-file:
    runs-on: ubuntu-latest
    steps:
    - name: Pushes file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'ranges.json'
        destination_repo: 'six2dez/ipcdn'
        user_email: 'example@email.com'
        user_name: 'six2dez'
        commit_message: 'Ip CDN ranges daily push from cdn.nuclei.sh'
      
