name: download_ranges

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Create local changes
      run: |
        curl -s -O ranges.txt https://cdn.nuclei.sh/
    - name: Commit files
      run: |
        git config --local user.email "six2dez@gmail.com"
        git config --local user.name "six2dez"
        git add -A ranges.txt
        git commit -m "CDN ip ranges daily push from cdn.nuclei.sh" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.API_TOKEN_GITHUB }}
        branch: ${{ github.ref }}
